modLoader="javafml"
loaderVersion="[{{forgeloader}},)"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId="{{modid}}"
version="${file.jarVersion}"
displayName="{{displayname}}"{{credits}}{{authors}}
updateJSONURL=""
displayURL=""
logoFile=""
description='''
{{description}}
'''